/**
 * Local development fixtures for Rukisha — a modest, deterministic sample
 * (tens to hundreds of rows), not the full illustrative dataset.
 * The full-scale dataset is generated by data/seed.py for an actual
 * Supabase project; these fixtures exist so the app renders real computed
 * KPIs locally before that project is provisioned (Phase 4 §10).
 */
import type {
  LoanAccountRow,
  RepaymentRow,
  TransactionRow,
  WalletRow,
  SavingsAccountRow,
} from "@/types/database";
import { seededRandom, uuid, randomInt, randomFloat, pick } from "./random";

const rand = seededRandom(1001);
const PRODUCTS: LoanAccountRow["product"][] = ["personal", "business", "asset_finance"];

export const rukishaLoans: LoanAccountRow[] = Array.from({ length: 260 }, () => {
  const daysOverdueBucket = pick(rand, ["current", "late", "default"] as const);
  const daysOverdue =
    daysOverdueBucket === "current"
      ? 0
      : daysOverdueBucket === "late"
        ? randomInt(rand, 1, 89)
        : randomInt(rand, 90, 300);
  return {
    id: uuid(rand),
    subsidiaryId: "rukisha",
    borrowerId: uuid(rand),
    product: pick(rand, PRODUCTS),
    outstandingBalance: randomFloat(rand, 5_000, 450_000),
    daysOverdue,
    status: "active",
  };
});

export const rukishaRepayments: RepaymentRow[] = rukishaLoans.map((loan) => {
  const amountDue = randomFloat(rand, 2_000, 40_000);
  const collectedFraction = pick(rand, [1, 1, 1, 0.8, 0.5, 0]);
  return {
    id: uuid(rand),
    loanAccountId: loan.id,
    amountDue,
    amountPaid: amountDue * collectedFraction,
    dueDate: "2026-06-15",
    paidDate: collectedFraction > 0 ? "2026-06-18" : null,
  };
});

export const rukishaWallets: WalletRow[] = Array.from({ length: 600 }, () => ({
  id: uuid(rand),
  subsidiaryId: "rukisha",
  status: pick(rand, ["active", "active", "active", "dormant"] as const),
  lastTransactionAt: "2026-06-29",
}));

const activeWalletIds = rukishaWallets.filter((w) => w.status === "active").map((w) => w.id);

export const rukishaTransactions: TransactionRow[] = Array.from({ length: 900 }, () => ({
  id: uuid(rand),
  subsidiaryId: "rukisha",
  walletId: pick(rand, activeWalletIds),
  type: pick(rand, ["merchant_payment", "transfer"] as const),
  amount: randomFloat(rand, 100, 25_000),
  createdAt: "2026-06-20",
}));

export const rukishaSavings: SavingsAccountRow[] = Array.from({ length: 500 }, () => ({
  id: uuid(rand),
  subsidiaryId: "rukisha",
  accountHolderId: uuid(rand),
  savingsType: pick(rand, ["goal_based", "goal_based", "pension_linked"] as const),
  balance: randomFloat(rand, 500, 60_000),
}));
